language: csharp

jobs:
  include:
    - stage: build
      script: msbuild /p:Configuration=Debug ConsoleApp1.sln
      
    - stage: test
      solution: ConsoleApp1.sln
      script:
        - dotnet restore
        - dotnet test
