language: csharp

jobs:
  include:
    - stage: build
      script: msbuild /p:Configuration=Debug ConsoleApp1.sln
      
    - stage: test
      dotnet: 2.0.9
      mono: none
      solution: ConsoleApp1.sln
      script:
        - dotnet restore
        - dotnet test
