language: csharp
solution: ConsoleApp1.sln

jobs:
  include:
    - stage: build
      script: msbuild /p:Configuration=Debug ConsoleApp1.sln
    - stage: test
      dotnet: 2.0.0
      script:
        - dotnet restore
        - dotnet test
