language: csharp
solution: ConsoleApp1.sln
install:
  - nuget restore ConsoleApp1.sln
script:
  - msbuild /p:Configuration=Debug ConsoleApp1.sln
  - powershell Get-ChildItem -Path C:\Users\entep04\ -recurse -include *.sln
